# Generated by Django 5.1.2 on 2024-10-21 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_notes', '0002_initial'),
        ('app_timers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timerblock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timersession',
            name='notes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_notes.note'),
        ),
        migrations.AddField(
            model_name='timersession',
            name='timer_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_timers.timerblock'),
        ),
    ]
