# Generated by Django 5.1.2 on 2024-10-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_timers', '0003_remove_timersession_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerblock',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
