# Generated by Django 5.1.2 on 2024-10-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_timers', '0008_alter_label_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
