# Generated by Django 5.1.2 on 2024-10-22 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_notes', '0002_initial'),
        ('app_timers', '0003_remove_timersession_end_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
