# Generated by Django 5.1.2 on 2024-10-21 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_statistics', '0001_initial'),
        ('app_timers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_timers.timersession'),
        ),
    ]
